### ISSUE TITLE
Uncaught TypeError: Cannot read property 'lineTextForScreenRow' of undefined

### ISSUE THREAD

**Issue by reslear** [tbremer/px-rem-tooltop-atom#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0-beta5 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [px-rem-tooltip](https://github.com/tbremer/px-rem-tooltop-atom) package 1.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'lineTextForScreenRow' of undefined

```
At C:\Users\admin\.atom\packages\px-rem-tooltip\lib\pxrem.js:36

TypeError: Cannot read property 'lineTextForScreenRow' of undefined
    at change (/packages/px-rem-tooltip/lib/pxrem.js:36:22)
    at /packages/px-rem-tooltip/lib/pxrem.js:97:14
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.17.0-beta5/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.17.0-beta5/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.17.0-beta5/resources/app/src/pane-container.js:280:1)
    at Pane.module.exports.Pane.setActiveItem (~/AppData/Local/atom/app-1.17.0-beta5/resources/app/src/pane.js:318:1)
    at Pane.module.exports.Pane.activateItem (~/AppData/Local/atom/app-1.17.0-beta5/resources/app/src/pane.js:471:1)
    at TabBarView.module.exports.TabBarView.onMouseDown (~/AppData/Local/atom/app-1.17.0-beta5/resources/app/node_modules/tabs/lib/tab-bar-view.js:693:1)
```

### Commands

```
     -1:00.1.0 core:confirm (input.hidden-input)
     -0:57.9.0 intentions:highlight (input.hidden-input)
     -0:57.8.0 core:paste (input.hidden-input)
     -0:56.7.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:55.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:54.4.0 core:backspace (input.hidden-input)
     -0:53.7.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:53.3.0 editor:newline (input.hidden-input)
     -0:52.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:52.3.0 editor:newline (input.hidden-input)
     -0:51.1.0 core:backspace (input.hidden-input)
     -0:50 editor:newline (input.hidden-input)
     -0:45 intentions:highlight (input.hidden-input)
     -0:44.7.0 core:copy (input.hidden-input)
     -0:42.7.0 core:paste (input.hidden-input)
     -0:41.5.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
atom-timestamp 0.0.8 
autoclose-html 0.23.0 
autocomplete-html-entities 0.1.0 
autocomplete-paths 1.0.5 
busy-signal 1.4.1 
highlight-selected 0.13.1 
indent-guide-improved 1.4.12 
intentions 1.1.2 
linter 2.1.4 
linter-csslint 1.3.4 
linter-htmlhint 1.3.3 
linter-jshint 3.1.0 
linter-ui-default 1.3.0 
livereload 0.4.4 
open-in-browser 0.5.0 
px-rem-tooltip 1.3.0 
Remote-FTP 0.10.7 
simple-copy-path 1.0.0 
simple-drag-drop-text 0.3.4 
```

**Comment by reslear** [comment]
https://yadi.sk/i/NelWFiwZ3HyB8m

**Comment by tbremer** [comment]
This is hopefully resolved with the latest release. Sorry for the long delay in fixing it, work got in the way.
